#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/cloud_final?useSSL=false
#
#    username:  root
#    password:  Thilanka@1234 # Enclose password in quotes if it contains special characters
#    hikari:
#      initialization-fail-timeout: 0
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect # Updated to MySQL 8 dialect
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#

#
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=false

    username:  ${DB_USERNAME}
    password:  ${DB_PASSWORD} # Enclose password in quotes if it contains special characters
    hikari:
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect # Updated to MySQL 8 dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update




